### ISSUE TITLE
Question about project architecture

### ISSUE THREAD

**Issue by gunzip** [geut/openapi-box#3]
I was in the process of implementing a similar tool for OpenAPI to Typebox conversion and runtime checks through Typebox validation. Then I came across this project, whose codebase seems understandable and well-written.

I wonder: is there any particular reason why you chose to implement the JSON Schema to Typebox conversion yourself instead of using https://github.com/xddq/schema2typebox?

Thank you for your effort!

**Comment by tinchoz49** [comment]
Hey @gunzip thank you for you feedback. I don't remember why I choose to do the conversion by myself I think is just did it because I was experimenting with the whole idea of this project. Then, since it worked for us, we keep it.
