### ISSUE TITLE
Unable to parse OpenAI schema

### ISSUE THREAD

**Issue by humphd** [geut/openapi-box#4]
I'm trying to create TypeBox types from the [OpenAI OpenAPI schema](https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml), but it's failing without much info:

```sh
yq eval -o=json resources/openapi.yaml > output/openai.json	
openapi-box output/openai.json -o openai.js
✖ ',' expected. (412:26)
  410 |   response_format: T.Optional(T.Union(cache['69fde07c72b934b7c91a2c1808b4bc59'],{"default":"json"})),
  411 |   temperature: T.Optional(T.Number({"default":0})),
> 412 |   timestamp_granularities[]: T.Optional(T.Array(cache['1272a49c80b3dc8bc038af92e19f1d72'],{"default":["segment"]})),
      |                          ^
  413 | }
  414 | cache['ce56d7a02eda5fc5e1e6ae8f44b7df4d'] = {
  415 |   file: T.String({"format":"binary"}),
```

Is this an issue in the schema, generated code, or openapi-box?

**Comment by humphd** [comment]
For now I've forced it to work by renaming a bunch of things in the OpenAI YAML:

- `timestamp_granularities[]` -> `timestamp_granularities`
- `self/harm` -> `self_harm`
- etc.

I'm not sure if there's a better approach, since these names are obviously going to be problematic in JS.

**Comment by tinchoz49** [comment]
those names are problematic but if the SwaggerParser validate the schema and thinks it's ok it means that it should be a valid schema for us too. So, yeah, this was an openapi-box issue. Fixed now.

**Comment by humphd** [comment]
@tinchoz49 thanks for such a quick turn-around on this, really appreciated!

**Comment by tinchoz49** [comment]
thank you for taking your time on reporting this!
