### ISSUE TITLE
Support YAML schemas

### ISSUE THREAD

**Issue by humphd** [geut/openapi-box#5]
Related to #4, I'm using openapi-box to work with the [OpenAI OpenAPI schema](https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml) which is YAML vs. JSON.  It would be nice if this was supported out of the box using something like [yaml](https://www.npmjs.com/package/yaml) to turn it JSON before parsing.

**Comment by tinchoz49** [comment]
Hey @humphd, we are using internally @apidevtools/swagger-parser that it's already has support for yaml. You can see in this test that is working: https://github.com/geut/openapi-box/blob/main/test/index.js#L331

**Comment by humphd** [comment]
Fantastic, thanks for clarifying.
