### ISSUE TITLE
Consider better type for generated cache variable

### ISSUE THREAD

**Issue by humphd** [geut/openapi-box#7]
This may not be something you want to address, but I'm trying to use the generated file in TypeScript.  That mostly works, but one thing that breaks is:

```js
const cache = {};
```

TypeScript is unhappy with this due to the keys:

> Element implicitly has an 'any' type because expression of type '"80a44415499f66d2e4772a7be3d417a1"' can't be used to index type '{}'.
  Property '80a44415499f66d2e4772a7be3d417a1' does not exist on type '{}' 

In my code I'm switching it to this, which side-steps it:

```ts
const cache: { [key: string]: any } = {};
```

**Comment by tinchoz49** [comment]
Hey @humphd can you give me an example of the code where you are getting this error? 

The `cache = {}` cannot be type `{ [key: string]: any }`,  I define it as a dynamic object to allow typescript to translate into a namespace structure.

Example:

```javascript
const cache = {}
cache.schema0 = Type.String()
cache.schema1 = Type.Number()
```

Typescript translate this into:

```typescript
import * as _sinclair_typebox from '@sinclair/typebox';

type TSchema = _sinclair_typebox.TSchema;
type Static<T extends TSchema> = _sinclair_typebox.Static<T>;
declare namespace cache {
    let schema0: _sinclair_typebox.TString;
    let schema1: _sinclair_typebox.TNumber;
}
```

**Comment by tinchoz49** [comment]
latest version remove the cache object
